### ISSUE TITLE
app crash with error on load map code

### ISSUE THREAD

**Issue by sakshi1501** [vinodlee/leetech_map_view#1]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.42.0)
[✓] Connected device (1 available)

• No issues found!

Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/AndroidRuntime(16966): Shutting down VM
E/AndroidRuntime(16966): FATAL EXCEPTION: main
E/AndroidRuntime(16966): Process: com.carauctionnetwork.publicautoauctions, PID: 16966
E/AndroidRuntime(16966): java.lang.NoSuchMethodError: No static method getNamedColorStateList(Landroid/content/res/TypedArray;Lorg/xmlpull/v1/XmlPullParser;Landroid/content/res/Resources$Theme;Ljava/lang/String;I)Landroid/content/res/ColorStateList; in class Landroidx/core/content/res/TypedArrayUtils; or its super classes (declaration of 'androidx.core.content.res.TypedArrayUtils' appears in /data/app/com.carauctionnetwork.publicautoauctions-1/base.apk)
E/AndroidRuntime(16966):        at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:765)
E/AndroidRuntime(16966):        at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:719)
E/AndroidRuntime(16966):        at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:682)
E/AndroidRuntime(16966):        at androidx.appcompat.widget.ResourceManagerInternal$VdcInflateDelegate.createFromXmlInner(ResourceManagerInternal.java:526)
E/AndroidRuntime(16966):        at androidx.appcompat.widget.ResourceManagerInternal.loadDrawableFromDelegates(ResourceManagerInternal.java:287)
E/AndroidRuntime(16966):        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:139)
E/AndroidRuntime(16966):        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
E/AndroidRuntime(16966):        at androidx.appcompat.widget.ResourceManagerInternal.checkVectorDrawableSetup(ResourceManagerInternal.java:504)
E/AndroidRuntime(16966):        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
E/AndroidRuntime(16966):        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:411)
E/AndroidRuntime(16966):        at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
E/AndroidRuntime(16966):        at androidx.appcompat.app.AppCompatDelegateImpl.attachToWindow(AppCompatDelegateImpl.java:647)
E/AndroidRuntime(16966):        at androidx.appcompat.app.AppCompatDelegateImpl.ensureWindow(AppCompatDelegateImpl.java:623)
E/AndroidRuntime(16966):        at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:350)
E/AndroidRuntime(16966):        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:105)
E/AndroidRuntime(16966):        at com.leetech.mapview.MapActivity.onCreate(MapActivity.kt:30)
E/AndroidRuntime(16966):        at android.app.Activity.performCreate(Activity.java:6298)
E/AndroidRuntime(16966):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
E/AndroidRuntime(16966):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608)
E/AndroidRuntime(16966):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725)
E/AndroidRuntime(16966):        at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(16966):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
E/AndroidRuntime(16966):        at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime(16966):        at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime(16966):        at android.app.ActivityThread.main(ActivityThread.java:5896)
E/AndroidRuntime(16966):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16966):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(16966):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
I/Process (16966): Sending signal. PID: 16966 SIG: 9

**Comment by Sreejith93** [comment]
The name 'CameraPosition' is defined in the libraries 'package:google_maps_flutter_platform_interface/src/types/camera.dart' and 'package:lee_map_view/camera_position.dart (via package:lee_map_view/map_view.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
